### ISSUE TITLE
bitcoind changed datadir

### ISSUE THREAD

**Issue by scriptzteam** [craigwatson/bitcoind-status#10]
i changed datadir in bitcoind.conf and now it wont output nothing? is there a ways to fix it?

**Comment by craigwatson** [comment]
Hi,

The status script communicates with bitcoind via RPC, so any issues with bitcoind aren't really my area I'm afraid.

What happens when you load the status page with `debug` switched to `true` in `php/config.php`?

Thanks,
Craig

**Comment by scriptzteam** [comment]
it works now, probably cache or so :)
