### ISSUE TITLE
Bytes sent/received sorting alphabetically

### ISSUE THREAD

**Issue by mlapaglia** [craigwatson/bitcoind-status#16]
The columns are sorting alphabetically instead of by data size.
![image](https://cloud.githubusercontent.com/assets/4184746/12738460/f0a36dce-c92e-11e5-9486-1519291bfa6c.png)

**Comment by mlapaglia** [comment]
#17 could be a possible fix for this

**Comment by craigwatson** [comment]
Thanks - much appreciated :)

#17 has been merged and I've verified that it fixes the bug.
