### ISSUE TITLE
help for some stuff related to altcoin

### ISSUE THREAD

**Issue by cyberpay** [craigwatson/bitcoind-status#19]
i am not able to get difficulty and charts displayed for altcoin any help would be appreciated. thanks

**Comment by craigwatson** [comment]
Hi,

It would be useful if you could provide a bit more detail - what altcoin are you using, do you have the stats collection cron set up, can you provide screenshots of how the charts currently look?

Thanks,
Craig

**Comment by cyberpay** [comment]
charts are not working at all, moreover its one of the new sha256d based altcoin now do i need to change rpcuser/rpcpassword/port # anywhere else (except config.php) in case they differ from the default 8332.

**Comment by craigwatson** [comment]
Hi,

No, you will only need to change the values in `config.php`. Your altcoin's daemon will also need to expose an RPC interface that is compatible with the upstream Bitcoind RPC calls (e.g. `getinfo`).

Unfortunately without more detail, I'm not able to help - I'll close this issue for now. If you're able to post your `config.php` file in full (with passwords redacted) as well as let me know which altcoin you're using, feel free to reopen :)

Cheers,
Craig
