### ISSUE TITLE
geolocate_peer_ip 'false' results in errors

### ISSUE THREAD

**Issue by bugmeat** [craigwatson/bitcoind-status#20]
After installing the latest version:

If geolocate_peer_ip is set to false in config.php, every IP box displays the message "Notice: Undefined index: geo_data in /web/public_html/.../public/bitcoin/html/template.html on line 153".

Works OK if set to true.

**Comment by craigwatson** [comment]
Hi,

This has been fixed in ed1f2db24381d887d9fc95bdaaeca15a3e164602 - thanks for the report :+1: 

Cheers,
Craig
