### ISSUE TITLE
Peer History

### ISSUE THREAD

**Issue by BeZazz** [craigwatson/bitcoind-status#22]
I noticed in peercount.php

// Include EasyBitcoin library and set up connection
require_once '/srv/www/bitcoind-status/php/easybitcoin.php';
$bitcoin = new Bitcoin($config['rpc_user'], $config['rpc_pass'], $config['rpc_host'], $config['rpc_port']);

The path to "easybitcoin.php" is hardcoded.

Also do you need to run "peercount.php"via a cron?

Thanks

**Comment by craigwatson** [comment]
Good spot, thanks! I'll get a fix for that committed shortly.

Yes, you'll need to run `peercount.php` and `stats.php` by cron (an example `crontab` line is in the Readme).

**Comment by BeZazz** [comment]
Ok,
Thanks mate :)

**Comment by craigwatson** [comment]
This is now fixed, see the commit above :)
