### ISSUE TITLE
RPC Error

### ISSUE THREAD

**Issue by DemonRx** [craigwatson/bitcoind-status#26]
Hi Craig, some reason the node-status page I'm running for my altcoin has stopped working. I believe it may have occured after the recent php update to version 5.5.9 including curl as well.

currently when i run >  curl -Ssk http://cryptostakers.com/node/stats.php  > i get the error >﻿
173.245.xxx.xxx is not in the whitelist (however this ip changes due to the server being behind cloudflare)

so i'm not sure if the php script is trying to do rpc call from outside the server? it shouldn't be doing this however, since it wasn't doing so before. 
and if i add the ip to the whitelist, and run the same curl, i get "rpc error".

If you could assist with this, please and thank you.

**Comment by craigwatson** [comment]
The stats script should be run from the server itself, not from any other source, and should be run against `localhost` and not the server's hostname.

**Comment by DemonRx** [comment]
root@CryptoCube:~# curl -Ssk http://localhost/node/stats.php

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>

<h1>Not Found</h1>

<p>The requested URL /node/stats.php was not found on this server.</p>

<hr>

<address>Apache/2.4.7 (Ubuntu) Server at localhost Port 80</address>
</body></html>

root@CryptoCube:~# curl -Ssk http://127.0.0.1/node/stats.php

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>

<h1>Not Found</h1>

<p>The requested URL /node/stats.php was not found on this server.</p>

<hr>

<address>Apache/2.4.7 (Ubuntu) Server at 127.0.0.1 Port 80</address>
</body></html>

/var/www/clients/client0/web1/web/node/  < that's the stats page location, i see it in from the terminal and filezilla

**Comment by craigwatson** [comment]
From the looks of the error, your server could be set up to use different virtual hosts based on the hostname. Is your daemon running on _the same_ server as the webserver running the scripts?

To be clear, the only _supported_ configuration is for the following, running _Bitcoin_. If you don't have this configuration, I can make a best guess at what is happening, but unfortunately no more than that.

![setup](https://dl.dropboxusercontent.com/u/3281664/btc.jpg)

**Comment by DemonRx** [comment]
Yes everything is on the same server, with cryptocube as the hostname. The
server itself is a VPS on a Hosting Provider...
and i have ispconfig for the cpanel, and cloudflare protection. also the
hosting provider has their own Dos protection.

If you need me to do something to help figure out the configuration I have setup, let me know.

I'll be around later, or tomorrow.

**Comment by craigwatson** [comment]
As I said, without knowing your exact server setup, complete with Apache virtual hosts, I'm unable to help any further.

My best guess is that your Apache configuration is not set to serve that DocumentRoot to requests for `localhost`, so I would suggest that you start there.

Your `rpc_host` entry in `php/config.php` file should be pointing to `localhost`, as should your cron commands using `curl`. If Apache is set up correctly, then everything else _should_ work.

**Comment by DemonRx** [comment]
https://www.howtoforge.com/perfect-server-ubuntu-14.04-apache2-php-mysql-pureftpd-bind-dovecot-ispconfig-3-p4

that's the setup i went by

**Comment by DemonRx** [comment]
ok fixed the DocumentRoot, 

now the output says ->

root@CryptoCube:/etc/apache2/sites-enabled# curl -Ssk http://localhost/node/stats.php
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>

<h1>Forbidden</h1>

<p>You don't have permission to access /node/stats.php
on this server.</p>

<hr>

<address>Apache/2.4.7 (Ubuntu) Server at localhost Port 80</address>
</body></html>

**Comment by craigwatson** [comment]
That now looks like file permission/ownership problems.

**Comment by DemonRx** [comment]
curl -Ssk http://localhost/node/stats.php

::1 is not in the whitelist

??

**Comment by craigwatson** [comment]
Try `127.0.0.1` instead of `localhost` - `::1` is IPv6.

**Comment by DemonRx** [comment]
curl -Ssk http://127.0.0.1/node/stats.php

RPC Error

**Comment by craigwatson** [comment]
Check your `php/config.php` - beyond this I'm unable to help further. If the `config.php` file is configured correctly, the RPC client will be able to respond.

**Comment by DemonRx** [comment]
should i change the config.php host to 127.0.0.1?

**Comment by craigwatson** [comment]
If your daemon is listening on IPv6, then `localhost` should work. If not, then it'll need to be `127.0.0.1`.

**Comment by DemonRx** [comment]
root@CryptoCube:~# lsof -i :8332
COMMAND     PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
DigiCubed 23264 root   19u  IPv4 3422706493      0t0  TCP *:8332 (LISTEN)
^^ The daemon

**Comment by DemonRx** [comment]
php/config.php setup ->
$config = array(
  // RPC
  'rpc_user'                  => 'digicube',
  'rpc_pass'                  => '[omitted]',
  'rpc_host'                  => 'localhost',
  'rpc_port'                  => '8332',
  'rpc_ssl'                   => false,
  'rpc_ssl_ca'                => null,

**Comment by craigwatson** [comment]
I'm not sure I can offer much help here - try `127.0.0.1` and see if it fixes the issue. Ultimately I only really support the script, anything on the RPC side is the user's responsibility.

**Comment by DemonRx** [comment]
http://cryptostakers.com/node/

**Comment by DemonRx** [comment]
LOL

i just testing with sprouts coindaemon it works.
there's something wrong with the digicube daemon, i'll have to contact the dev see what he fucked up in it.

**Comment by craigwatson** [comment]
No problem, I'll close this issue.

**Comment by DemonRx** [comment]
ty for your help today
