### ISSUE TITLE
Setting up [Node Links]

### ISSUE THREAD

**Issue by DemonRx** [craigwatson/bitcoind-status#27]
Hi Craig,

Sorry forgot to ask you how to setup the 'Node Links" in the config.php 

I just want to put the DigiCube Logo and link it to Bitcointalk Thread

**Comment by craigwatson** [comment]
There should be enough information in the Readme to get that working.

What have you tried so far?

**Comment by DemonRx** [comment]
I understand this is the format >

_```
    'node_links' => array (
        array (
            'name' => 'Bitnodes.21.co http://Bitnodes.21.co',
            'image'=> 'img/bitnodes.21.co.png',
            'link' => 'https://bitnodes.21.co/nodes/[IP]-[PORT]/
https://bitnodes.21.co/nodes/[IP]-[PORT]/'
        ),
        array (
            ...
        )
    ),_

_```_

_The way it's in my config.php:_

 'node_links'
        => array(
                       'name'=> 'DigiCube',
                       'image'=> 'node/img/cube.png',
                       'link' => 'https://bitcointalk.org/index.php?topic=1211692.new;topicseen#new'
),

however, this doesn't seem to work

**Comment by craigwatson** [comment]
Is the path to the image correct? Also, there should be two arrays, as per the readme example.

**Comment by DemonRx** [comment]
/var/www/clients/client0/web1/web/node/img/cube.png

that's its location. and config.php is in node/php

**Comment by craigwatson** [comment]
TBH that path means nothing to me, because I don't know how your webserver is configured. Use of the script sssumed a certain amount of skills in working with web servers.

As per the readme, there should be two arrays, not one.

**Comment by DemonRx** [comment]
K, Working now :)  > https://cryptostakers.com/node

Now to figure out why the peer chart isn't showing ?

**Comment by craigwatson** [comment]
Again, as per the readme, you need a minimum number of data points, so the cron needs to be set up and running successfully, and `display_peer_chart` In `php/config.php` should be `true`.

**Comment by DemonRx** [comment]
#Node Stats Page
*/5 \* \* \* \* curl -Ssk http://127.0.0.1/node/stats.php > /dev/null
*/5 \* \* \* \* curl -Ssk http://127.0.0.1/node/peercount.php > /dev/null

yup setup in cron and working. I forgot to add the peercount to cron,
thanks for the reminder. Now i just wait for the chart to show.

**Comment by DemonRx** [comment]
When i set **display_ip, display_version, display_bitnodes_info** **=> true**
they don't show any values

**Comment by craigwatson** [comment]
That would be because the

**Comment by craigwatson** [comment]
The Bitnodes display looks up your IP address against bitnodes.21.co - if you're running an altcoin your nodes won't be listed as they only crawl the Bitcoin node network.

The other switches rely on data being retrieved over RPC, so if the data isn't being provided in the correct format, it will be ignored, and I don't support RPC issues or altcoins.

**Comment by DemonRx** [comment]
Oh ok, then otherwise everything is working fine for what I need for this node. Thanks for all your help Craig, appreciate it!
