### ISSUE TITLE
pingtime error after upgrading to bitcoin 13.0

### ISSUE THREAD

**Issue by bugmeat** [craigwatson/bitcoind-status#28]
After upgrading to bitcoin 13.0, in the ping column where previously the ping showed '0', it gives an error:

Notice: Undefined index: pingtime in /web/public_html/jazzpie.com/public/bitcoin/html/template.html on line 183
0

The ping displays normal if the ping result is anything other than '0'.

I have never seen this error before, and now have it on both of my servers after the upgrade to bitcoin 13.0.

**Comment by craigwatson** [comment]
Hi,

Thanks for raising this - I currently don't have a bitcoind 13.0 environment to test, so I'll let you know when I can replicate the issue.

Thanks,
Craig

**Comment by craigwatson** [comment]
Can you please pull the latest code and check that the fix above solves your issue?

The `pingtime` value is reported by the bitcoin daemon via RPC, and it seems that not all peers include that value, so the status page now displays "Unavailable" if the RPC call for that peer fails to return a value.

**Comment by bugmeat** [comment]
Craig Watson wrote:

> Can you please pull the latest code and check that the fix above solves
> your issue?
> 
> The |pingtime| value is reported by the bitcoin daemon via RPC, and it
> seems that not all peers include that value, so the status page now
> displays "Unavailable" if the RPC call for that peer fails to return a
> value.

Works fine with the latest template.html. It now displays 'Unavailable'
instead of the error message.

Thanks,

Al
