### ISSUE TITLE
Add Dockerfile for container deployment

### ISSUE THREAD

**Issue by blakev** [craigwatson/bitcoind-status#33]

**Comment by PhilPhonic** [comment]
Sadly, this is not that simple. I gave it a quick shot and ran into multiple problems.
Many thinks don't work from scratch, when putting this web-application into a docker container.
For example displaying of bitcoin daemon uptime won't work. From inside the container, you are unable to get information about processes running outside the container (and that's where bitcoind is running).
This is one of the reasons why you dockerize applications. Your application is in some kind of sandbox here.

I know, this doesn't solve your request. But I hope this explanation helps a bit to understand why there isn't a dockerfile (yet?).

**Comment by blakev** [comment]
Hmm...maybe I'll make an all-in-one container that runs this and bitcoind. If I do I'll update you.

Thanks for trying!

**Comment by craigwatson** [comment]
Hi all,

I'm closing this issue for now - if anyone does end up with a Dockerised version, please do feel free to reopen this issue or create a PR :)

Thanks,
Craig
