### ISSUE TITLE
method not found with latest bitcoin core from github

### ISSUE THREAD

**Issue by jpuk** [craigwatson/bitcoind-status#35]
Hello.

I'm just trying to get going with bitcoind-status and am getting the following error on index.php "method not found" when running against the latest version of bitcoin core from the git master branch. 0.15.99.

When run against a bitcoin abc node bitcoind status produces the expected results.

Is there anyway I can debug what method is missing in the latest core release?

**Comment by craigwatson** [comment]
Hi,

You can set `debug` to `true` in `config.php` - although a proper PHP error message would be better.

Can you please post an excerpt of your PHP error logs?

**Comment by craigwatson** [comment]
Hi,

As this issue hasn't seen any activity in over a month, I'll close it for now.

Please do feel free to reopen if this is still a problem, though it would be appreciated if you could include the PHP errors displayed and any debug information :)

Thanks
Craig
