### ISSUE TITLE
getinfo() is going to be deprecated in Bitcoin Core 0.16 onwards

### ISSUE THREAD

**Issue by jamesmacwhite** [craigwatson/bitcoind-status#43]
Just a heads up for the future. Possible reworking needed.

> WARNING: getinfo is deprecated and will be fully removed in 0.16. Projects should transition to using getblockchaininfo, getnetworkinfo, and getwalletinfo before upgrading to 0.16

https://github.com/bitcoin/bitcoin/issues/11382
https://github.com/bitcoin/bitcoin/issues/11671

**Comment by cfahrni** [comment]
quick workaround for 0.16:
```
pi@raspberrypi:/var/www/html $ diff php/functions.php php/functions.php.bak
54c54
<     $data = $bitcoin->getblockchaininfo();
---
>     $data = $bitcoin->getinfo();
```
there is more testing and reworking needed i suppose.
