### ISSUE TITLE
Include basic .htaccess to deny access to stats.php and peercount.php

### ISSUE THREAD

**Issue by jamesmacwhite** [craigwatson/bitcoind-status#44]
Not sure what you think but for users who host bitcoind-status on Apache. It might be beneficial to include a `.htaccess` with some default rules. Particularly, for protecting the `stats.php` and `peercount.php` pages. I know a whitelisting system is in place, but every request still have to be checked by the app. Blocking at the server level might be more beneficial from a security point of view. With Apache it would be easily achieved with something like the examples below.

```
# Apache 2.4
<FilesMatch "^(stats\.php|peercount\.php)$">
    Require local
</FilesMatch>

# Apache 2.2
<FilesMatch "^(stats\.php|peercount\.php)$">
    Order Deny,Allow 
    Deny from all 
    Allow from 127.0.0.1
</FilesMatch>
```

Instant 403 to any client that tries to access those pages outside of localhost, never touches the PHP app.

I personally deploy this code within the VirtualHost config, but it would work fine in `.htaccess`

Just my thoughts.

**Comment by craigwatson** [comment]
Nice idea, but I don't think that this should be the concern of the app - given that the app was written to be as portable as possible.

Also, if a user should want to open up access from other hosts (a bad idea, but possible nevertheless), then with this approach there would be two whitelists to manage.

This isn't to say that a server administrator shouldn't be taking steps to secure applications, but in this instance it's a bit of an over-reach IMO.

**Comment by jamesmacwhite** [comment]
@craigwatson Sure. Totally understand. Perhaps something for the docs maybe.
