### ISSUE TITLE
qr donation image does not support segwit adresses

### ISSUE THREAD

**Issue by Boesboes** [craigwatson/bitcoind-status#46]
If you put a segwit adres in the donation variable the generated qr code is not a valled adress.

To reproduce:
Enter a segwit address as donation address and scan the code with a qr scanner. (i used bread on ios)

**Comment by craigwatson** [comment]
Thanks for raising this - I don't have a live node to validate this against but have a Vagrant environment running on the testnet. Can you provide a segwit address to test with?

**Comment by Boesboes** [comment]
Hey Craig,

Thank you for your time to look at this. I have a full node running here: https://rambling.online/bitcoind/ 
Also added a segwit address in the config file. The segwit address was generated with Electrum 3.0.3.

**Comment by Boesboes** [comment]
Update. I tested some more but the problem maybe electrum. With segwit they went for only Bech32 support. When i create a segwit address with my ledger it works(P2SH address). So it maybe not your QR generator but wallets not supporting bech32 yet.

For testing:
Status page with bech32 adres: https://rambling.online/bitcoind/
Status page with P2SH adres: https://rambling.online/bitcoind-test/

**Comment by Boesboes** [comment]
And tested again your qr code is fine. if you use the btc.com wallet you can scan it without problems. problem was bread wallet not supporting bech32 addresses. Sorry for opening this issue what wasn't a problem in your code.
