### ISSUE TITLE
Connected Peers List Limited to 8 Peers

### ISSUE THREAD

**Issue by dagnyc** [craigwatson/bitcoind-status#51]
Hi,

How can I make the page show all connected peers even if it is thousands? This is what I was hoping for but don't see a way to change it.

Any help would be greatly appreciated

Thanks

**Comment by Boesboes** [comment]
It isn't limited to 8. I have for example 20 connected peers in my list atm.

I believe 8 connections is the limit if you do not have port 8333 forwarded. Also bitcoin has a default 125 max connections. To extend to thousand you also need to adjust your maxconnections settings.

**Comment by craigwatson** [comment]
Hi @dagnyc,

Really sorry for the delay, as @Boesboes has mentioned, there is no such limit (either within the status page or `bitcoind`).

Thanks,
Craig
