### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by greg121** [craigwatson/bitcoind-status#6]
Can you give me some more information on how to install this (running ubuntu)?
- I have a full node
- I have apache2 + php5
- I edited the config file

**Comment by craigwatson** [comment]
Hi Greg,

Can you give some more information about your errors? Do you get any output?

Thanks,
Craig

**Comment by craigwatson** [comment]
Hi Greg,

I'm closing this issue for now, please feel free to add more detail on your problem and configuration and I'll take a look :)

Craig
